---
name: merge_empty_pr
on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  merge_empty_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git diff
        uses: KazukiHayase/review-git-diff-action@v1.0.0
        with:
          threshold: 0
          message: "⚠️  Git diff exceeds 0, won't be merged automatically."
      - name: "Check Subject Is 'I pledge'"
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^I pledge(\n.*)*$'
          error: 'Subject is not I pledge'
